package git

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// devNullPath is the sentinel endpoint git prints for added and deleted
// files in ---/+++ headers.
const devNullPath = "/dev/null"

// diffNoNewlineMarker is git's exact, locale-stable (we force LC_ALL=C)
// end-of-hunk marker; a body line only reaches it when it matches whole.
const diffNoNewlineMarker = `\ No newline at end of file`

// DiffLineType classifies one line inside a hunk: unchanged context, an
// addition on the new side, or a deletion on the old side.
type DiffLineType string

const (
	DiffLineContext DiffLineType = "context"
	DiffLineAdd     DiffLineType = "add"
	DiffLineDel     DiffLineType = "del"
)

// DiffLine is one hunk line. OldNum/NewNum are 1-based line numbers in the
// old and new file; 0 means the line does not exist on that side. Text
// excludes the leading +/-/space marker.
type DiffLine struct {
	Type      DiffLineType `json:"type"`
	OldNum    int          `json:"oldNum"`
	NewNum    int          `json:"newNum"`
	Text      string       `json:"text"`
	NoNewline bool         `json:"noNewline,omitempty"`
}

// DiffHunk is one @@-delimited block. Header keeps the raw "@@ ... @@"
// line, including any trailing section heading git prints after it.
type DiffHunk struct {
	Header   string     `json:"header"`
	OldStart int        `json:"oldStart"`
	OldCount int        `json:"oldCount"`
	NewStart int        `json:"newStart"`
	NewCount int        `json:"newCount"`
	Lines    []DiffLine `json:"lines"`
}

// FileDiff is the parsed unified diff of a single file. The two path
// endpoints carry the names as git sees them: OldPath is empty for adds,
// NewPath for deletes, and both stay empty for sections without name
// headers (a zero-byte new file), where the caller already knows the
// requested path. Change classifies the section and defaults to
// ChangeModified; mode-only edits keep both modes with zero hunks.
type FileDiff struct {
	OldPath    string     `json:"oldPath"`
	NewPath    string     `json:"newPath"`
	Change     Change     `json:"change"`
	Binary     bool       `json:"binary,omitempty"`
	Similarity int        `json:"similarity,omitempty"`
	OldMode    string     `json:"oldMode,omitempty"`
	NewMode    string     `json:"newMode,omitempty"`
	Hunks      []DiffHunk `json:"hunks"`
}

// parseUnifiedDiff parses `git diff`-style patch output (issue #24). The
// parser only ever sees output generated by this package's own git
// invocations, whose headers are pinned by machine flags (see buildGitCmd),
// so anything before the first hunk that is not a recognized header line is
// ignored for forward compatibility, while a truncated or over-full hunk is
// a hard parse_failed error.
func parseUnifiedDiff(data []byte) ([]FileDiff, error) {
	p := &diffParser{cur: -1}
	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		if err := p.feed(line); err != nil {
			return nil, err
		}
	}
	if p.inHunk && (p.oldRem > 0 || p.newRem > 0) {
		return nil, parseFailed("hunk truncated at end of output: " + p.hunk().Header)
	}
	for i := range p.files {
		if p.files[i].Change == "" {
			p.files[i].Change = ChangeModified
		}
	}
	return p.files, nil
}

type diffParser struct {
	files  []FileDiff
	cur    int // index into files of the current section; -1 before the first
	inHunk bool
	// current hunk bookkeeping: remaining lines per side and the next
	// 1-based number on each side
	oldRem, newRem int
	oldNum, newNum int
}

func (p *diffParser) feed(line string) error {
	if p.inHunk {
		// a context line or the EOF marker can arrive after both counts are
		// spent (the marker always trails the last body line), so the hunk
		// closes lazily; any other line ends it
		if line == diffNoNewlineMarker || strings.HasPrefix(line, " ") || p.oldRem > 0 || p.newRem > 0 {
			return p.feedHunk(line)
		}
		p.inHunk = false
	}
	switch {
	case line == "":
		// blank separator between sections, or the final newline
	case strings.HasPrefix(line, "diff --git "):
		p.files = append(p.files, FileDiff{Hunks: []DiffHunk{}})
		p.cur = len(p.files) - 1
	case strings.HasPrefix(line, "--- "), strings.HasPrefix(line, "+++ "):
		if p.cur < 0 {
			return parseFailed("file header outside any section: " + line)
		}
		f := p.file()
		value := line[4:]
		if line[0] == '+' {
			return p.setPath(&f.NewPath, value, "b/", ChangeDeleted)
		}
		return p.setPath(&f.OldPath, value, "a/", ChangeAdded)
	case strings.HasPrefix(line, "@@ "):
		return p.startHunk(line)
	default:
		return p.feedExtended(line)
	}
	return nil
}

// extendedKeys are the section headers whose values the parser needs; any
// other line between headers (index, zdiff, future keys) is ignored.
var extendedKeys = []string{
	"old mode ", "new mode ", "new file mode ", "deleted file mode ",
	"similarity index ", "rename from ", "rename to ", "Binary files ",
}

func (p *diffParser) feedExtended(line string) error {
	key := ""
	for _, k := range extendedKeys {
		if strings.HasPrefix(line, k) {
			key = k
			break
		}
	}
	if key == "" {
		return nil
	}
	if p.cur < 0 {
		return parseFailed("extended header outside any section: " + line)
	}
	f, value := p.file(), line[len(key):]
	switch key {
	case "old mode ":
		f.OldMode = value
	case "new mode ":
		f.NewMode = value
	case "new file mode ":
		f.NewMode, f.Change = value, ChangeAdded
	case "deleted file mode ":
		f.OldMode, f.Change = value, ChangeDeleted
	case "similarity index ":
		n, err := strconv.Atoi(strings.TrimSuffix(value, "%"))
		if err != nil || n < 0 || n > 100 {
			return parseFailed("malformed similarity index: " + line)
		}
		f.Similarity = n
	case "rename from ":
		path, err := unquoteGitPath(value)
		if err != nil {
			return err
		}
		f.OldPath, f.Change = path, ChangeRenamed
	case "rename to ":
		path, err := unquoteGitPath(value)
		if err != nil {
			return err
		}
		f.NewPath, f.Change = path, ChangeRenamed
	case "Binary files ":
		return p.setBinaryEndpoints(f, value)
	}
	return nil
}

// setBinaryEndpoints decodes "<old> and <new> differ". The grammar is
// ambiguous when a raw name contains " and "; callers then fill the
// requested path back in, which single-file diffs always know.
func (p *diffParser) setBinaryEndpoints(f *FileDiff, body string) error {
	if !strings.HasSuffix(body, " differ") {
		return parseFailed("malformed binary files header: " + body)
	}
	left, right, ok := strings.Cut(strings.TrimSuffix(body, " differ"), " and ")
	if !ok {
		return parseFailed("malformed binary files header: " + body)
	}
	var err error
	if f.OldPath, _, err = decodeEndpoint(left, "a/"); err != nil {
		return err
	}
	if f.NewPath, _, err = decodeEndpoint(right, "b/"); err != nil {
		return err
	}
	f.Binary = true
	return nil
}

func (p *diffParser) feedHunk(line string) error {
	if line == "" {
		return parseFailed("empty line inside hunk")
	}
	h := p.hunk()
	switch line[0] {
	case ' ':
		if p.oldRem == 0 || p.newRem == 0 {
			return parseFailed("context line beyond declared range: " + line)
		}
		p.oldRem--
		p.newRem--
		h.Lines = append(h.Lines, DiffLine{Type: DiffLineContext, OldNum: p.oldNum, NewNum: p.newNum, Text: line[1:]})
		p.oldNum++
		p.newNum++
	case '-':
		if p.oldRem == 0 {
			return parseFailed("removed line beyond declared range: " + line)
		}
		p.oldRem--
		h.Lines = append(h.Lines, DiffLine{Type: DiffLineDel, OldNum: p.oldNum, Text: line[1:]})
		p.oldNum++
	case '+':
		if p.newRem == 0 {
			return parseFailed("added line beyond declared range: " + line)
		}
		p.newRem--
		h.Lines = append(h.Lines, DiffLine{Type: DiffLineAdd, NewNum: p.newNum, Text: line[1:]})
		p.newNum++
	case '\\':
		if line != diffNoNewlineMarker {
			return parseFailed("unexpected line inside hunk: " + line)
		}
		n := len(h.Lines)
		if n == 0 {
			return parseFailed(`no-newline marker without a preceding line`)
		}
		h.Lines[n-1].NoNewline = true
	default:
		return parseFailed("unexpected line inside hunk: " + line)
	}
	return nil
}

func (p *diffParser) file() *FileDiff {
	return &p.files[p.cur]
}

func (p *diffParser) hunk() *DiffHunk {
	f := p.file()
	return &f.Hunks[len(f.Hunks)-1]
}

func (p *diffParser) startHunk(line string) error {
	if p.cur < 0 {
		return parseFailed("hunk outside any file section: " + line)
	}
	oldStart, oldCount, newStart, newCount, err := parseRangeHeaders(line)
	if err != nil {
		return err
	}
	p.file().Hunks = append(p.file().Hunks, DiffHunk{
		Header:   line,
		OldStart: oldStart,
		OldCount: oldCount,
		NewStart: newStart,
		NewCount: newCount,
		Lines:    []DiffLine{},
	})
	p.inHunk = true
	p.oldRem, p.newRem = oldCount, newCount
	p.oldNum, p.newNum = oldStart, newStart
	return nil
}

// parseRangeHeaders decodes "@@ -old[,count] +new[,count] @@ [heading]",
// where an omitted count means exactly one line (git's default -U3 output
// for a one-line file is "@@ -1 +1 @@").
func parseRangeHeaders(line string) (oldStart, oldCount, newStart, newCount int, err error) {
	rest, ok := strings.CutPrefix(line, "@@ -")
	if !ok {
		return 0, 0, 0, 0, parseFailed("malformed hunk header: " + line)
	}
	oldText, rest, ok := strings.Cut(rest, " +")
	if !ok {
		return 0, 0, 0, 0, parseFailed("malformed hunk header: " + line)
	}
	newText, rest, ok := strings.Cut(rest, " @@")
	if !ok || (rest != "" && !strings.HasPrefix(rest, " ")) {
		return 0, 0, 0, 0, parseFailed("malformed hunk header: " + line)
	}
	if oldStart, oldCount, err = parseRange(oldText, line); err != nil {
		return
	}
	if newStart, newCount, err = parseRange(newText, line); err != nil {
		return
	}
	return oldStart, oldCount, newStart, newCount, nil
}

func parseRange(text, header string) (start, count int, err error) {
	startText, countText, hasCount := strings.Cut(text, ",")
	start, err = strconv.Atoi(startText)
	if err != nil || start < 0 {
		return 0, 0, parseFailed("malformed hunk header: " + header)
	}
	count = 1
	if hasCount {
		count, err = strconv.Atoi(countText)
		if err != nil || count < 0 {
			return 0, 0, parseFailed("malformed hunk header: " + header)
		}
	}
	return start, count, nil
}

// setPath decodes one endpoint of the file pair from a ---/+++ header and
// records /dev/null as the empty path with its matching Change. The path
// may be followed by a TAB and timestamp; quoted form `"a/..."` is used
// whenever the name contains characters git considers unusual.
func (p *diffParser) setPath(dst *string, token, side string, onDevNull Change) error {
	path, devNull, err := decodeEndpoint(token, side)
	if err != nil {
		return err
	}
	*dst = path
	if devNull {
		p.file().Change = onDevNull
	}
	return nil
}

func decodeEndpoint(token, side string) (path string, devNull bool, err error) {
	name, _, _ := strings.Cut(token, "\t")
	path, err = unquoteGitPath(name)
	if err != nil {
		return "", false, err
	}
	if path == devNullPath {
		return "", true, nil
	}
	return strings.TrimPrefix(path, side), false, nil
}

// unquoteGitPath decodes git's C-style path quoting (core.quotePath): a
// quoted name starts and ends with a double quote and escapes non-printable
// and non-ASCII bytes as \NNN octal sequences plus the usual single-letter
// escapes. Unquoted names pass through unchanged.
func unquoteGitPath(s string) (string, error) {
	if !strings.HasPrefix(s, "\"") {
		return s, nil
	}
	if len(s) < 2 || !strings.HasSuffix(s, "\"") {
		return "", parseFailed("malformed quoted path: " + s)
	}
	body := s[1 : len(s)-1]
	var b strings.Builder
	for i := 0; i < len(body); i++ {
		c := body[i]
		if c != '\\' {
			b.WriteByte(c)
			continue
		}
		i++
		if i >= len(body) {
			return "", parseFailed("dangling escape in quoted path: " + s)
		}
		switch e := body[i]; e {
		case '"', '\\':
			b.WriteByte(e)
		case 'a':
			b.WriteByte('\a')
		case 'b':
			b.WriteByte('\b')
		case 'f':
			b.WriteByte('\f')
		case 'n':
			b.WriteByte('\n')
		case 'r':
			b.WriteByte('\r')
		case 't':
			b.WriteByte('\t')
		case 'v':
			b.WriteByte('\v')
		default:
			if e < '0' || e > '7' {
				return "", parseFailed("unknown escape \\" + string(e) + " in quoted path: " + s)
			}
			val := int(e - '0')
			for d := 0; d < 2 && i+1 < len(body) && body[i+1] >= '0' && body[i+1] <= '7'; d++ {
				i++
				val = val*8 + int(body[i]-'0')
			}
			b.WriteByte(byte(val))
		}
	}
	return b.String(), nil
}

// DiffOption configures diff generation (issue #24).
type DiffOption func(*diffConfig)

type diffConfig struct {
	unified *int
}

// WithContextLines requests n lines of surrounding context per hunk,
// overriding git's default of 3. n may be 0. Untracked-file diffs ignore
// it: their single synthesized hunk already covers the whole file.
func WithContextLines(n int) DiffOption {
	return func(c *diffConfig) { c.unified = &n }
}

func diffFlags(opts []DiffOption) ([]string, error) {
	var cfg diffConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	if cfg.unified == nil {
		return nil, nil
	}
	if *cfg.unified < 0 {
		return nil, &GitError{Code: CodeValidationFailed, Message: "context lines cannot be negative", ExitCode: -1}
	}
	return []string{fmt.Sprintf("-U%d", *cfg.unified)}, nil
}

// DiffWorkingFile returns the diff of one repository-relative path.
// staged=false compares work tree against the index; staged=true compares
// the index against HEAD. Untracked files never appear in git diff, so the
// unstaged side synthesizes their diff against /dev/null from the file
// bytes, matching the shape git prints once the file is staged - binary
// heuristic included.
func (r *Repo) DiffWorkingFile(ctx context.Context, path string, staged bool, opts ...DiffOption) (*FileDiff, error) {
	clean, err := cleanDiffPath(path)
	if err != nil {
		return nil, err
	}
	unified, err := diffFlags(opts)
	if err != nil {
		return nil, err
	}
	// :(literal) keeps glob characters in real file names inert: without
	// it a path such as "weird*.txt" could match unrelated files
	args := []string{"diff", "--no-ext-diff"}
	args = append(args, unified...)
	if staged {
		args = append(args, "--staged")
	}
	out, _, err := runGit(ctx, r.path, append(args, "--", ":(literal)"+clean)...)
	if err != nil {
		return nil, err
	}
	fd, err := diffFileFromOutput(out, clean)
	if err != nil {
		return nil, err
	}
	if fd != nil {
		return fd, nil
	}
	if staged {
		return unchangedFileDiff(clean), nil
	}
	tracked, err := r.isTracked(ctx, clean)
	if err != nil {
		return nil, err
	}
	if tracked {
		return unchangedFileDiff(clean), nil
	}
	return diffUntrackedFile(clean, filepath.Join(r.path, filepath.FromSlash(clean)))
}

// diffFileFromOutput enforces the single-file contract on one-path git
// diff output: no sections yields nil for the caller to interpret, one
// section yields the filled FileDiff, many reject as validation failures.
func diffFileFromOutput(out []byte, path string) (*FileDiff, error) {
	files, err := parseUnifiedDiff(out)
	if err != nil {
		return nil, err
	}
	switch len(files) {
	case 0:
		return nil, nil
	case 1:
		return fillDiffPaths(&files[0], path), nil
	default:
		return nil, &GitError{Code: CodeValidationFailed, Message: "path matches more than one file: " + path, ExitCode: -1}
	}
}

// DiffCommitFile returns the diff of one path within one commit, taken
// against the commit's first parent. The merge decision (issue #24):
// -m --first-parent. Plain `git show` of a merge prints the combined --cc
// diff, which hides every file that matches any parent - side-branch
// content disappears; plain -m repeats each file once per parent. A
// first-parent view matches what history UIs show, and root commits fall
// back to diffing against the empty tree. The single-path pathspec also
// breaks git's rename pairing, so a renamed file renders as a full add
// (new side) or delete (old side); DiffCommitFiles carries the R status.
func (r *Repo) DiffCommitFile(ctx context.Context, hash, path string, opts ...DiffOption) (*FileDiff, error) {
	if err := checkCommitHash(hash); err != nil {
		return nil, err
	}
	clean, err := cleanDiffPath(path)
	if err != nil {
		return nil, err
	}
	unified, err := diffFlags(opts)
	if err != nil {
		return nil, err
	}
	pre := append([]string{"--no-ext-diff"}, unified...)
	out, _, err := runGit(ctx, r.path,
		showCommitDiffArgs(hash, pre, []string{"--", ":(literal)" + clean})...)
	if err != nil {
		return nil, err
	}
	if fd, err := diffFileFromOutput(out, clean); err != nil || fd != nil {
		return fd, err
	}
	return unchangedFileDiff(clean), nil
}

func (r *Repo) isTracked(ctx context.Context, path string) (bool, error) {
	_, _, err := runGit(ctx, r.path, "ls-files", "--error-unmatch", "--", ":(literal)"+path)
	if err == nil {
		return true, nil
	}
	var ge *GitError
	if errors.As(err, &ge) && ge.Code == CodeCommandFailed && ge.ExitCode == 1 {
		return false, nil
	}
	return false, err
}

// cleanDiffPath validates a repository-relative, single-file diff path and
// normalizes it to slash form for pathspecs and result paths.
func cleanDiffPath(path string) (string, error) {
	validation := func(msg string) error {
		return &GitError{Code: CodeValidationFailed, Message: msg, ExitCode: -1}
	}
	if path == "" {
		return "", validation("diff path required")
	}
	clean := filepath.ToSlash(filepath.Clean(path))
	// IsAbs is drive-letter based on Windows; a leading slash means the
	// same thing to git there and would surface as its exit-128 fatal
	if filepath.IsAbs(path) || strings.HasPrefix(clean, "/") {
		return "", validation("diff path must be relative to the repository: " + path)
	}
	if clean == "." || clean == ".." || strings.HasPrefix(clean, "../") {
		return "", validation("diff path must stay inside the repository: " + path)
	}
	return clean, nil
}

// fillDiffPaths restores the name git omits in header-only sections (a
// zero-byte add, a mode-only change): callers already know the path.
func fillDiffPaths(f *FileDiff, path string) *FileDiff {
	if f.OldPath != "" || f.NewPath != "" {
		return f
	}
	switch f.Change {
	case ChangeAdded:
		f.NewPath = path
	case ChangeDeleted:
		f.OldPath = path
	default:
		f.OldPath, f.NewPath = path, path
	}
	return f
}

func unchangedFileDiff(path string) *FileDiff {
	return &FileDiff{OldPath: path, NewPath: path, Change: ChangeModified, Hunks: []DiffHunk{}}
}

// diffUntrackedFile turns raw file bytes into the added-file diff git
// would print after staging, against /dev/null.
func diffUntrackedFile(path, fullPath string) (*FileDiff, error) {
	data, err := os.ReadFile(fullPath)
	if err != nil {
		if info, serr := os.Stat(fullPath); serr == nil && info.IsDir() {
			return nil, &GitError{Code: CodeValidationFailed, Message: "untracked directory has no single-file diff: " + path, ExitCode: -1}
		}
		return nil, &GitError{Code: CodePathMissing, Message: path + " is not readable: " + err.Error(), ExitCode: -1}
	}
	// git records the exec bit as 100755 once the file is staged; mirror
	// that here so the untracked view matches the staged view
	mode := "100644"
	if info, serr := os.Stat(fullPath); serr == nil && info.Mode()&0o111 != 0 {
		mode = "100755"
	}
	fd := &FileDiff{NewPath: path, Change: ChangeAdded, NewMode: mode, Hunks: []DiffHunk{}}
	// git's convert.c rule: only the first 8000 bytes decide binary-ness
	if bytes.IndexByte(data[:min(len(data), 8000)], 0) >= 0 {
		fd.Binary = true
		return fd, nil
	}
	lines, unterminated := splitContentLines(data)
	if len(lines) == 0 {
		return fd, nil
	}
	header := fmt.Sprintf("@@ -0,0 +1,%d @@", len(lines))
	if len(lines) == 1 {
		header = "@@ -0,0 +1 @@"
	}
	h := DiffHunk{Header: header, NewStart: 1, NewCount: len(lines), Lines: make([]DiffLine, 0, len(lines))}
	for i, text := range lines {
		h.Lines = append(h.Lines, DiffLine{
			Type: DiffLineAdd, NewNum: i + 1, Text: text,
			NoNewline: unterminated && i == len(lines)-1,
		})
	}
	fd.Hunks = append(fd.Hunks, h)
	return fd, nil
}

// splitContentLines counts a final unterminated fragment as a line,
// mirroring git's line numbering for files without a trailing newline.
func splitContentLines(data []byte) (lines []string, unterminated bool) {
	if len(data) == 0 {
		return nil, false
	}
	text := string(data)
	unterminated = !strings.HasSuffix(text, "\n")
	if !unterminated {
		text = text[:len(text)-1]
	}
	return strings.Split(text, "\n"), unterminated
}

// DiffCommitFiles returns the per-file summary of one commit against its
// first parent (same merge rule as DiffCommitFile): git status letter,
// insertions and deletions, with rename detection on (-M). Neither
// --name-status nor --numstat alone carries both the letter and the
// counts, so we run both passes and join them per path.
func (r *Repo) DiffCommitFiles(ctx context.Context, hash string) ([]CommitFileStat, error) {
	if err := checkCommitHash(hash); err != nil {
		return nil, err
	}
	raws := make([][]byte, 0, 2)
	for _, flags := range [][]string{{"--name-status", "-M"}, {"--numstat", "-M"}} {
		out, err := r.showZ(ctx, hash, flags...)
		if err != nil {
			return nil, err
		}
		raws = append(raws, out)
	}
	return parseCommitFileStats(raws[0], raws[1])
}

// changedFilesFromStatus converts a NUL-parsed --name-status stream into
// summary entries; counts and binary flags stay zero until
// parseCommitFileStats joins the numstat pass.
func changedFilesFromStatus(out []byte) ([]CommitFileStat, error) {
	statuses, err := parseNameStatusZ(out)
	if err != nil {
		return nil, err
	}
	files := make([]CommitFileStat, 0, len(statuses))
	for _, st := range statuses {
		files = append(files, CommitFileStat{
			Change: st.change, Path: st.path, OldPath: st.oldPath, Similarity: st.similarity,
		})
	}
	return files, nil
}

// parseCommitFileStats joins the two decoded show passes; a status record
// without its numstat counterpart means git output was cut short.
func parseCommitFileStats(namesOut, countsOut []byte) ([]CommitFileStat, error) {
	stats, err := changedFilesFromStatus(namesOut)
	if err != nil {
		return nil, err
	}
	counts, err := parseNumstatZ(countsOut)
	if err != nil {
		return nil, err
	}
	for i := range stats {
		cn, ok := counts[stats[i].Path]
		if !ok {
			return nil, parseFailed("numstat record missing for " + stats[i].Path)
		}
		stats[i].Binary, stats[i].Added, stats[i].Deleted = cn.binary, cn.added, cn.deleted
	}
	return stats, nil
}

func (r *Repo) showZ(ctx context.Context, hash string, flags ...string) ([]byte, error) {
	out, _, err := runGit(ctx, r.path, showCommitDiffArgs(hash, append(flags, "-z"), nil)...)
	return out, err
}

func checkCommitHash(hash string) error {
	// leading "-" would be swallowed as an option; argv passes verbatim but
	// the option boundary still needs guarding
	if hash == "" || strings.HasPrefix(hash, "-") {
		return &GitError{Code: CodeValidationFailed, Message: "commit hash required", ExitCode: -1}
	}
	return nil
}

func showCommitDiffArgs(hash string, pre, post []string) []string {
	args := []string{"show", "--format=", "-m", "--first-parent"}
	args = append(args, pre...)
	args = append(args, hash)
	return append(args, post...)
}

type nameStatusEntry struct {
	change     Change
	path       string
	oldPath    string
	similarity int
}

// parseNameStatusZ decodes NUL-terminated --name-status records:
// "<status>\0<path>\0", where R and C statuses are followed by old and
// new paths instead of a single one.
func parseNameStatusZ(out []byte) ([]nameStatusEntry, error) {
	if len(out) == 0 {
		return nil, nil
	}
	tokens := strings.Split(strings.TrimSuffix(string(out), "\x00"), "\x00")
	var res []nameStatusEntry
	for i := 0; i < len(tokens); i++ {
		status := tokens[i]
		if status == "" {
			return nil, parseFailed("empty name-status record")
		}
		e := nameStatusEntry{change: changeFromLetter(status[0])}
		if score := status[1:]; score != "" {
			n, err := strconv.Atoi(score)
			if err != nil {
				return nil, parseFailed("malformed name-status score: " + status)
			}
			e.similarity = n
		}
		switch status[0] {
		case 'R', 'C':
			if i+2 >= len(tokens) {
				return nil, parseFailed("truncated rename record: " + status)
			}
			e.oldPath, e.path = tokens[i+1], tokens[i+2]
			i += 2
		default:
			if i+1 >= len(tokens) {
				return nil, parseFailed("truncated name-status record: " + status)
			}
			e.path = tokens[i+1]
			i++
		}
		res = append(res, e)
	}
	return res, nil
}

type numstatEntry struct {
	added, deleted int
	binary         bool
}

// parseNumstatZ decodes NUL-terminated --numstat records:
// "<add>\t<del>\t<path>\0". Rename and copy records have an empty path
// slot followed by old and new paths; binary files report "-".
func parseNumstatZ(out []byte) (map[string]numstatEntry, error) {
	res := map[string]numstatEntry{}
	if len(out) == 0 {
		return res, nil
	}
	tokens := strings.Split(strings.TrimSuffix(string(out), "\x00"), "\x00")
	for i := 0; i < len(tokens); i++ {
		addText, rest, ok := strings.Cut(tokens[i], "\t")
		if !ok {
			return nil, parseFailed("malformed numstat record: " + tokens[i])
		}
		delText, path, hasPath := strings.Cut(rest, "\t")
		if !hasPath {
			return nil, parseFailed("malformed numstat record: " + tokens[i])
		}
		var e numstatEntry
		if addText == "-" && delText == "-" {
			e.binary = true
		} else {
			added, err := strconv.Atoi(addText)
			if err != nil {
				return nil, parseFailed("malformed numstat counts: " + tokens[i])
			}
			deleted, err := strconv.Atoi(delText)
			if err != nil {
				return nil, parseFailed("malformed numstat counts: " + tokens[i])
			}
			e.added, e.deleted = added, deleted
		}
		if path == "" {
			if i+2 >= len(tokens) {
				return nil, parseFailed("truncated numstat rename record")
			}
			path = tokens[i+2]
			i += 2
		}
		res[path] = e
	}
	return res, nil
}

// CommitFileStat is one changed file in a commit summary. Path is the new
// side; OldPath is set for renames. Binary marks files whose line counts
// git cannot compute.
type CommitFileStat struct {
	Change     Change `json:"change"`
	Path       string `json:"path"`
	OldPath    string `json:"oldPath,omitempty"`
	Similarity int    `json:"similarity,omitempty"`
	Binary     bool   `json:"binary,omitempty"`
	Added      int    `json:"added"`
	Deleted    int    `json:"deleted"`
}
