package git

import (
	"strconv"
	"strings"
)

// diffNoNewlineMarker is git's exact, locale-stable (we force LC_ALL=C)
// end-of-hunk marker; a body line only reaches it when it matches whole.
const devNullPath = "/dev/null"

const diffNoNewlineMarker = `\ No newline at end of file`

// DiffLineType classifies one line inside a hunk: unchanged context, an
// addition on the new side, or a deletion on the old side.
type DiffLineType string

const (
	DiffLineContext DiffLineType = "context"
	DiffLineAdd     DiffLineType = "add"
	DiffLineDel     DiffLineType = "del"
)

// DiffLine is one hunk line. OldNum/NewNum are 1-based line numbers in the
// old and new file; 0 means the line does not exist on that side. Text
// excludes the leading +/-/space marker.
type DiffLine struct {
	Type      DiffLineType `json:"type"`
	OldNum    int          `json:"oldNum"`
	NewNum    int          `json:"newNum"`
	Text      string       `json:"text"`
	NoNewline bool         `json:"noNewline,omitempty"`
}

// DiffHunk is one @@-delimited block. Header keeps the raw "@@ ... @@"
// line, including any trailing section heading git prints after it.
type DiffHunk struct {
	Header   string     `json:"header"`
	OldStart int        `json:"oldStart"`
	OldCount int        `json:"oldCount"`
	NewStart int        `json:"newStart"`
	NewCount int        `json:"newCount"`
	Lines    []DiffLine `json:"lines"`
}

// FileDiff is the parsed unified diff of a single file. The two path
// endpoints carry the names as git sees them: OldPath is empty for adds,
// NewPath for deletes, and both stay empty for sections without name
// headers (a zero-byte new file), where the caller already knows the
// requested path. Change classifies the section and defaults to
// ChangeModified; mode-only edits keep both modes with zero hunks.
type FileDiff struct {
	OldPath    string     `json:"oldPath"`
	NewPath    string     `json:"newPath"`
	Change     Change     `json:"change"`
	Binary     bool       `json:"binary,omitempty"`
	Similarity int        `json:"similarity,omitempty"`
	OldMode    string     `json:"oldMode,omitempty"`
	NewMode    string     `json:"newMode,omitempty"`
	Hunks      []DiffHunk `json:"hunks"`
}

// parseUnifiedDiff parses `git diff`-style patch output (issue #24). The
// parser only ever sees output generated by this package's own git
// invocations, whose headers are pinned by machine flags (see buildGitCmd),
// so anything before the first hunk that is not a recognized header line is
// ignored for forward compatibility, while a truncated or over-full hunk is
// a hard parse_failed error.
func parseUnifiedDiff(data []byte) ([]FileDiff, error) {
	p := &diffParser{cur: -1}
	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		if err := p.feed(line); err != nil {
			return nil, err
		}
	}
	if p.inHunk && (p.oldRem > 0 || p.newRem > 0) {
		return nil, diffParseError("hunk truncated at end of output: " + p.hunk().Header)
	}
	for i := range p.files {
		if p.files[i].Change == "" {
			p.files[i].Change = ChangeModified
		}
	}
	return p.files, nil
}

type diffParser struct {
	files  []FileDiff
	cur    int // index into files of the current section; -1 before the first
	inHunk bool
	// current hunk bookkeeping: remaining lines per side and the next
	// 1-based number on each side
	oldRem, newRem int
	oldNum, newNum int
}

func (p *diffParser) feed(line string) error {
	if p.inHunk {
		// a context line or the EOF marker can arrive after both counts are
		// spent (the marker always trails the last body line), so the hunk
		// closes lazily; any other line ends it
		if line == diffNoNewlineMarker || strings.HasPrefix(line, " ") || p.oldRem > 0 || p.newRem > 0 {
			return p.feedHunk(line)
		}
		p.inHunk = false
	}
	switch {
	case line == "":
		// blank separator between sections, or the final newline
	case strings.HasPrefix(line, "diff --git "):
		p.files = append(p.files, FileDiff{Hunks: []DiffHunk{}})
		p.cur = len(p.files) - 1
	case strings.HasPrefix(line, "--- "), strings.HasPrefix(line, "+++ "):
		if p.cur < 0 {
			return diffParseError("file header outside any section: " + line)
		}
		f := p.file()
		value := line[4:]
		if line[0] == '+' {
			return p.setPath(&f.NewPath, value, "b/", ChangeDeleted)
		}
		return p.setPath(&f.OldPath, value, "a/", ChangeAdded)
	case strings.HasPrefix(line, "@@ "):
		return p.startHunk(line)
	default:
		return p.feedExtended(line)
	}
	return nil
}

// extendedKeys are the section headers whose values the parser needs; any
// other line between headers (index, zdiff, future keys) is ignored.
var extendedKeys = []string{
	"old mode ", "new mode ", "new file mode ", "deleted file mode ",
	"similarity index ", "rename from ", "rename to ", "Binary files ",
}

func (p *diffParser) feedExtended(line string) error {
	key := ""
	for _, k := range extendedKeys {
		if strings.HasPrefix(line, k) {
			key = k
			break
		}
	}
	if key == "" {
		return nil
	}
	if p.cur < 0 {
		return diffParseError("extended header outside any section: " + line)
	}
	f, value := p.file(), line[len(key):]
	switch key {
	case "old mode ":
		f.OldMode = value
	case "new mode ":
		f.NewMode = value
	case "new file mode ":
		f.NewMode, f.Change = value, ChangeAdded
	case "deleted file mode ":
		f.OldMode, f.Change = value, ChangeDeleted
	case "similarity index ":
		n, err := strconv.Atoi(strings.TrimSuffix(value, "%"))
		if err != nil || n < 0 || n > 100 {
			return diffParseError("malformed similarity index: " + line)
		}
		f.Similarity = n
	case "rename from ":
		path, err := unquoteGitPath(value)
		if err != nil {
			return err
		}
		f.OldPath, f.Change = path, ChangeRenamed
	case "rename to ":
		path, err := unquoteGitPath(value)
		if err != nil {
			return err
		}
		f.NewPath, f.Change = path, ChangeRenamed
	case "Binary files ":
		return p.setBinaryEndpoints(f, value)
	}
	return nil
}

// setBinaryEndpoints decodes "<old> and <new> differ". The grammar is
// ambiguous when a raw name contains " and "; callers then fill the
// requested path back in, which single-file diffs always know.
func (p *diffParser) setBinaryEndpoints(f *FileDiff, body string) error {
	if !strings.HasSuffix(body, " differ") {
		return diffParseError("malformed binary files header: " + body)
	}
	left, right, ok := strings.Cut(strings.TrimSuffix(body, " differ"), " and ")
	if !ok {
		return diffParseError("malformed binary files header: " + body)
	}
	var err error
	if f.OldPath, _, err = decodeEndpoint(left, "a/"); err != nil {
		return err
	}
	if f.NewPath, _, err = decodeEndpoint(right, "b/"); err != nil {
		return err
	}
	f.Binary = true
	return nil
}

func (p *diffParser) feedHunk(line string) error {
	if line == "" {
		return diffParseError("empty line inside hunk")
	}
	h := p.hunk()
	switch line[0] {
	case ' ':
		if p.oldRem == 0 || p.newRem == 0 {
			return diffParseError("context line beyond declared range: " + line)
		}
		p.oldRem--
		p.newRem--
		h.Lines = append(h.Lines, DiffLine{Type: DiffLineContext, OldNum: p.oldNum, NewNum: p.newNum, Text: line[1:]})
		p.oldNum++
		p.newNum++
	case '-':
		if p.oldRem == 0 {
			return diffParseError("removed line beyond declared range: " + line)
		}
		p.oldRem--
		h.Lines = append(h.Lines, DiffLine{Type: DiffLineDel, OldNum: p.oldNum, Text: line[1:]})
		p.oldNum++
	case '+':
		if p.newRem == 0 {
			return diffParseError("added line beyond declared range: " + line)
		}
		p.newRem--
		h.Lines = append(h.Lines, DiffLine{Type: DiffLineAdd, NewNum: p.newNum, Text: line[1:]})
		p.newNum++
	case '\\':
		if line != diffNoNewlineMarker {
			return diffParseError("unexpected line inside hunk: " + line)
		}
		n := len(h.Lines)
		if n == 0 {
			return diffParseError(`no-newline marker without a preceding line`)
		}
		h.Lines[n-1].NoNewline = true
	default:
		return diffParseError("unexpected line inside hunk: " + line)
	}
	return nil
}

func (p *diffParser) file() *FileDiff {
	return &p.files[p.cur]
}

func (p *diffParser) hunk() *DiffHunk {
	f := p.file()
	return &f.Hunks[len(f.Hunks)-1]
}

func (p *diffParser) startHunk(line string) error {
	if p.cur < 0 {
		return diffParseError("hunk outside any file section: " + line)
	}
	oldStart, oldCount, newStart, newCount, err := parseRangeHeaders(line)
	if err != nil {
		return err
	}
	p.file().Hunks = append(p.file().Hunks, DiffHunk{
		Header:   line,
		OldStart: oldStart,
		OldCount: oldCount,
		NewStart: newStart,
		NewCount: newCount,
		Lines:    []DiffLine{},
	})
	p.inHunk = true
	p.oldRem, p.newRem = oldCount, newCount
	p.oldNum, p.newNum = oldStart, newStart
	return nil
}

// parseRangeHeaders decodes "@@ -old[,count] +new[,count] @@ [heading]",
// where an omitted count means exactly one line (git's default -U3 output
// for a one-line file is "@@ -1 +1 @@").
func parseRangeHeaders(line string) (oldStart, oldCount, newStart, newCount int, err error) {
	rest, ok := strings.CutPrefix(line, "@@ -")
	if !ok {
		return 0, 0, 0, 0, diffParseError("malformed hunk header: " + line)
	}
	oldText, rest, ok := strings.Cut(rest, " +")
	if !ok {
		return 0, 0, 0, 0, diffParseError("malformed hunk header: " + line)
	}
	newText, rest, ok := strings.Cut(rest, " @@")
	if !ok || (rest != "" && !strings.HasPrefix(rest, " ")) {
		return 0, 0, 0, 0, diffParseError("malformed hunk header: " + line)
	}
	if oldStart, oldCount, err = parseRange(oldText, line); err != nil {
		return
	}
	if newStart, newCount, err = parseRange(newText, line); err != nil {
		return
	}
	return oldStart, oldCount, newStart, newCount, nil
}

func parseRange(text, header string) (start, count int, err error) {
	startText, countText, hasCount := strings.Cut(text, ",")
	start, err = strconv.Atoi(startText)
	if err != nil || start < 0 {
		return 0, 0, diffParseError("malformed hunk header: " + header)
	}
	count = 1
	if hasCount {
		count, err = strconv.Atoi(countText)
		if err != nil || count < 0 {
			return 0, 0, diffParseError("malformed hunk header: " + header)
		}
	}
	return start, count, nil
}

// setPath decodes one endpoint of the file pair from a ---/+++ header and
// records /dev/null as the empty path with its matching Change. The path
// may be followed by a TAB and timestamp; quoted form `"a/..."` is used
// whenever the name contains characters git considers unusual.
func (p *diffParser) setPath(dst *string, token, side string, onDevNull Change) error {
	path, devNull, err := decodeEndpoint(token, side)
	if err != nil {
		return err
	}
	*dst = path
	if devNull {
		p.file().Change = onDevNull
	}
	return nil
}

func decodeEndpoint(token, side string) (path string, devNull bool, err error) {
	name, _, _ := strings.Cut(token, "\t")
	path, err = unquoteGitPath(name)
	if err != nil {
		return "", false, err
	}
	if path == devNullPath {
		return "", true, nil
	}
	return strings.TrimPrefix(path, side), false, nil
}

// unquoteGitPath decodes git's C-style path quoting (core.quotePath): a
// quoted name starts and ends with a double quote and escapes non-printable
// and non-ASCII bytes as \NNN octal sequences plus the usual single-letter
// escapes. Unquoted names pass through unchanged.
func unquoteGitPath(s string) (string, error) {
	if !strings.HasPrefix(s, "\"") {
		return s, nil
	}
	if len(s) < 2 || !strings.HasSuffix(s, "\"") {
		return "", diffParseError("malformed quoted path: " + s)
	}
	body := s[1 : len(s)-1]
	var b strings.Builder
	for i := 0; i < len(body); i++ {
		c := body[i]
		if c != '\\' {
			b.WriteByte(c)
			continue
		}
		i++
		if i >= len(body) {
			return "", diffParseError("dangling escape in quoted path: " + s)
		}
		switch e := body[i]; e {
		case '"', '\\':
			b.WriteByte(e)
		case 'a':
			b.WriteByte('\a')
		case 'b':
			b.WriteByte('\b')
		case 'f':
			b.WriteByte('\f')
		case 'n':
			b.WriteByte('\n')
		case 'r':
			b.WriteByte('\r')
		case 't':
			b.WriteByte('\t')
		case 'v':
			b.WriteByte('\v')
		default:
			if e < '0' || e > '7' {
				return "", diffParseError("unknown escape \\" + string(e) + " in quoted path: " + s)
			}
			val := int(e - '0')
			for d := 0; d < 2 && i+1 < len(body) && body[i+1] >= '0' && body[i+1] <= '7'; d++ {
				i++
				val = val*8 + int(body[i]-'0')
			}
			b.WriteByte(byte(val))
		}
	}
	return b.String(), nil
}

func diffParseError(msg string) error {
	return &GitError{Code: CodeParseFailed, Message: msg, ExitCode: -1}
}
