// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentRepo(arg1) {
  return window['go']['main']['App']['AddRecentRepo'](arg1);
}

export function GetRecentRepos() {
  return window['go']['main']['App']['GetRecentRepos']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenRepository(arg1) {
  return window['go']['main']['App']['OpenRepository'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}
