// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function AddRecentRepo(arg1:string):Promise<main.CallResult>;

export function GetRecentRepos():Promise<Array<config.RecentRepo>>;

export function GetSettings():Promise<config.Settings>;

export function OpenFolder():Promise<main.FolderDialogResult>;

export function OpenRepository(arg1:string):Promise<main.OpenRepositoryResult>;

export function SetSettings(arg1:config.Settings):Promise<main.CallResult>;
