// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentRepo(arg1) {
  return window['go']['main']['App']['AddRecentRepo'](arg1);
}

export function ClearHostToken(arg1) {
  return window['go']['main']['App']['ClearHostToken'](arg1);
}

export function Commit(arg1, arg2) {
  return window['go']['main']['App']['Commit'](arg1, arg2);
}

export function DiscardFiles(arg1) {
  return window['go']['main']['App']['DiscardFiles'](arg1);
}

export function GetHostToken(arg1) {
  return window['go']['main']['App']['GetHostToken'](arg1);
}

export function GetRecentRepos() {
  return window['go']['main']['App']['GetRecentRepos']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSubmodules() {
  return window['go']['main']['App']['GetSubmodules']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenRepository(arg1) {
  return window['go']['main']['App']['OpenRepository'](arg1);
}

export function OpenSubmodule(arg1) {
  return window['go']['main']['App']['OpenSubmodule'](arg1);
}

export function SaveHostToken(arg1, arg2) {
  return window['go']['main']['App']['SaveHostToken'](arg1, arg2);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function StageAll() {
  return window['go']['main']['App']['StageAll']();
}

export function StageFiles(arg1) {
  return window['go']['main']['App']['StageFiles'](arg1);
}

export function SubmoduleAdd(arg1, arg2) {
  return window['go']['main']['App']['SubmoduleAdd'](arg1, arg2);
}

export function SubmoduleDeinit(arg1) {
  return window['go']['main']['App']['SubmoduleDeinit'](arg1);
}

export function SubmoduleInitUpdate(arg1) {
  return window['go']['main']['App']['SubmoduleInitUpdate'](arg1);
}

export function SubmoduleRemove(arg1) {
  return window['go']['main']['App']['SubmoduleRemove'](arg1);
}

export function SubmoduleUpdate(arg1) {
  return window['go']['main']['App']['SubmoduleUpdate'](arg1);
}

export function UnstageAll() {
  return window['go']['main']['App']['UnstageAll']();
}

export function UnstageFiles(arg1) {
  return window['go']['main']['App']['UnstageFiles'](arg1);
}
